### ISSUE TITLE
关于第一次IAAA500错误

### ISSUE THREAD

**Issue by RainshawGao** [Bruuuuuuce/PKUAutoSubmit#1]
是由于之前某一次IAAA升级，直接打开IAAA进行登陆门户都会出现该错误。必须先访问门户，然后获取对应的cookie/session再被重定向至IAAA 
相似的情形可参见 https://github.com/zhongxinghong/PKUAutoElective/issues/35

**Comment by Bruuuuuuce** [comment]
非常感谢！

发件人: Rainshaw
发送时间: 2020年10月5日 1:06
收件人: Bruuuuuuce/PKUAutoSubmit
抄送: Subscribed
主题: [Bruuuuuuce/PKUAutoSubmit] 关于第一次IAAA500错误 (#1)

是由于之前某一次IAAA升级，直接打开IAAA进行登陆门户都会出现该错误。必须先访问门户，然后获取对应的cookie/session再被重定向至IAAA
相似的情形可参见 zhongxinghong/PKUAutoElective#35
