### ISSUE TITLE
写了面向小白的教程

### ISSUE THREAD

**Issue by hayschan** [Bruuuuuuce/PKUAutoSubmit#10]
[每天自动备案](https://haysc.tech/2020/10/17/pku-auto-beian/)
![image](https://user-images.githubusercontent.com/25737801/96337378-4bb3c980-10b9-11eb-8f8d-508e119b207c.png)

如果有帮助的话，麻烦挂在README里。🙏

**Comment by Bruuuuuuce** [comment]
十分感谢，建议通知该版本作者YOUSIKI放在其README中

发件人: Hays Chan
发送时间: 2020年10月17日 20:43
收件人: Bruuuuuuce/PKUAutoSubmit
抄送: Subscribed
主题: [Bruuuuuuce/PKUAutoSubmit] 写了面向小白的教程 (#10)

每天自动备案

如果有帮助的话，麻烦挂在README里。🙏

**Comment by hayschan** [comment]
好的 👌
