### ISSUE TITLE
纯HTTP的自动填报

### ISSUE THREAD

**Issue by yzs981130** [Bruuuuuuce/PKUAutoSubmit#12]
貌似使用selenium会不定期出现
```
selenium.common.exceptions.TimeoutException: Message: 
Screenshot: available via screen
```
的错误，必须要手动re-run很影响体验，比如  https://github.com/YOUSIKI/PKUAutoSubmit/runs/1271524630，https://github.com/yzs981130/PKUAutoSubmit/actions?query=is%3Afailure，https://github.com/Bruuuuuuce/PKUAutoSubmit/issues/9#issuecomment-710149802

仔细研究了一下整个iaaa到simso的认证过程，写了一个纯HTTP的交互，见https://github.com/yzs981130/autoSubmit ，也支持了github actions，使用方法与 @YOUSIKI 一样

写的很糙，错误处理都没做，readme也还没写，欢迎pr，也欢迎直接移植到本repo，省去用selenium和phantomjs的烦恼

**Comment by Bruuuuuuce** [comment]
感谢您的错误反馈，已找到相关错误诱发原因，正着手修复。同时感谢发布使用其他交互方式的解决方案，本项目仅因是selenium练习项目故采用该方案，可能存在诸多问题等待完善，希望贵repo有更佳表现。

发件人: 叶志晟
发送时间: 2020年10月19日 5:43
收件人: Bruuuuuuce/PKUAutoSubmit
抄送: Subscribed
主题: [Bruuuuuuce/PKUAutoSubmit] 纯HTTP的自动填报 (#12)

貌似使用selenium会不定期出现
selenium.common.exceptions.TimeoutException: Message: 

Screenshot: available via screen

的错误，必须要手动re-run很影响体验，比如 https://github.com/YOUSIKI/PKUAutoSubmit/runs/1271524630，https://github.com/yzs981130/PKUAutoSubmit/actions?query=is%3Afailure，https://github.com/Bruuuuuuce/PKUAutoSubmit/issues/9#issuecomment-710149802
仔细研究了一下整个iaaa到simso的认证过程，写了一个纯HTTP的交互，见https://github.com/yzs981130/autoSubmit，也支持了github actions，使用方法与 @YOUSIKI 一样
写的很糙，错误处理都没做，readme也还没写，欢迎pr，也欢迎直接移植到本repo，省去用selenium和phantomjs的烦恼
