### ISSUE TITLE
能否使用多个配置文件进行填报

### ISSUE THREAD

**Issue by Vittorio-Veneto-www** [Bruuuuuuce/PKUAutoSubmit#14]
可以几个人一起填，大概

**Comment by Bruuuuuuce** [comment]
好的，提上日程

**Comment by Vittorio-Veneto-www** [comment]
还发现了一个小bug，OSError: [Errno 8] Exec format error
https://stackoverflow.com/questions/27606653/oserror-errno-8-exec-format-error这里面似乎说了解决方案

Traceback (most recent call last):
  File "main.py", line 29, in <module>
    executable_path='./phantomjs/bin/phantomjs')
  File "/local/lib/python3.7/site-packages/selenium/webdriver/phantomjs/webdriver.py", line 56, in __init__
    self.service.start()
  File "/local/lib/python3.7/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: './phantomjs/bin/phantomjs'

**Comment by Bruuuuuuce** [comment]
请问出现在了哪个系统的版本中

**Comment by Bruuuuuuce** [comment]
请确定服务器的系统，说到了root权限很可能是Linux系统，暂时还未适配Linux，其实也换一个PhantomJS版本就行，会在之后考虑适配

**Comment by Bruuuuuuce** [comment]
当然去官网（https://phantomjs.org/download.html）下一个Linux版的然后稍微改一改main.py的调用部分就可以，也可以等我更新

**Comment by Vittorio-Veneto-www** [comment]
实话说我配置了挺久才弄懂究竟是什么意思，不仅要下phantomjs还要改个名
能否将linux版的phantomjs也置于项目内，或者为linux提供一个单独的发行版

**Comment by Bruuuuuuce** [comment]
在10.21已发布Linux对应的release

发件人: Vittorio-Veneto-www
发送时间: 2020年10月21日 21:31
收件人: Bruuuuuuce/PKUAutoSubmit
抄送: Bruce Ding; Comment
主题: Re: [Bruuuuuuce/PKUAutoSubmit] 能否使用多个配置文件进行填报 (#14)

实话说我配置了挺久才弄懂究竟是什么意思，不仅要下phantomjs还要改个名
能否将linux版的phantomjs也置于项目内，或者为linux提供一个单独的发行版

**Comment by Bruuuuuuce** [comment]
> 可以几个人一起填，大概

已支持多人填报
