### ISSUE TITLE
对新版出入校进行了适配

### ISSUE THREAD

**Issue by AowuCat** [Bruuuuuuce/PKUAutoSubmit#21]
https://github.com/AowuCat/PKUAutoSubmit2
参考了你的代码，在此表示感谢~

**Comment by Bruuuuuuce** [comment]
非常优秀！

**Comment by Bruuuuuuce** [comment]
我已经在考虑修改以适配了，若是以此方式每日例行申请可行的话（院系每天都能审核通过）。当然绝大部分同学不久后即将返乡，而新学期政策仍有很大变数，所以还未着手编写，总之感谢你的工作！

**Comment by Bruuuuuuce** [comment]
不过可以放在discussion里面hhh
