### ISSUE TITLE
DOM不会更新，一直卡在登陆中

### ISSUE THREAD

**Issue by mickelliu** [Bruuuuuuce/PKUAutoSubmit#27]
作者大大你好，今天貌似自动报备没有成功。貌似是因为一直会卡在“登陆中"没有跳转，所以找不到“全部”按钮也就是”id=all"。

但是输错误的账户密码还是会显示账户密码错误。

请救救没法苗的孩子

![1634277920(1)](https://user-images.githubusercontent.com/20177526/137440140-9449d4fb-17b5-4f4f-904c-0a3b3a9fa46d.jpg)

**Comment by mickelliu** [comment]
貌似是phantomJS的问题...我换成chromedriver就能用了

**Comment by Bruuuuuuce** [comment]
> 貌似是phantomJS的问题...我换成chromedriver就能用了

非常感谢您的issue，我因已经毕业离校无法访问完整的portal，没想到现在还是需要日常报备TT
若您可以解决这个问题衷心希望您可以提交一个PR我放进去，我也会尝试解决一下，再次感谢

**Comment by mickelliu** [comment]
> > 貌似是phantomJS的问题...我换成chromedriver就能用了
> 
> 非常感谢您的issue，我因已经毕业离校无法访问完整的portal，没想到现在还是需要日常报备TT 若您可以解决这个问题衷心希望您可以提交一个PR我放进去，我也会尝试解决一下，再次感谢

没有苗是这样的。听说苗了两针的话会自动加入白名单，之后就不用报备了。
