### ISSUE TITLE
10.24测试报备截图失败

### ISSUE THREAD

**Issue by y1cunhui** [Bruuuuuuce/PKUAutoSubmit#29]
在func.py的screencapture函数中卡住了

TimeOutException,尝试调大timeout也不行

完整错误信息：
Traceback (most recent call last):
  File "D:\***\PKUAutoSubmit\main.py", line 64, in <module>
    go('config.ini')
  File "D:\***\PKUAutoSubmit\main.py", line 38, in go
    run(driver_pjs, userName, password, campus, reason, destination, track,
  File "D:\***\PKUAutoSubmit\func.py", line 254, in run
    screen_capture(driver, path)
  File "D:\***\PKUAutoSubmit\func.py", line 219, in screen_capture
    WebDriverWait(driver, 20).until(
  File "C:\Users\***\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 89, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
Backtrace:
        Ordinal0 [0x0061BDE3+2473443]
        Ordinal0 [0x005B6661+2057825]
        Ordinal0 [0x004C2438+1057848]
        Ordinal0 [0x004EC7DB+1230811]
        Ordinal0 [0x00516712+1402642]
        Ordinal0 [0x0050571A+1333018]
        Ordinal0 [0x00514ABF+1395391]
        Ordinal0 [0x005055AB+1332651]
        Ordinal0 [0x004E2104+1188100]
        Ordinal0 [0x004E2F59+1191769]
        GetHandleVerifier [0x007A2266+1549718]
        GetHandleVerifier [0x0084D4A7+2250711]
        GetHandleVerifier [0x006A718B+521403]
        GetHandleVerifier [0x006A6229+517465]
        Ordinal0 [0x005BB79D+2078621]
        Ordinal0 [0x005BFB58+2095960]
        Ordinal0 [0x005BFC92+2096274]
        Ordinal0 [0x005C9541+2135361]
        BaseThreadInitThunk [0x76F6FA29+25]
        RtlGetAppContainerNamedObjectPath [0x770D7A9E+286]
        RtlGetAppContainerNamedObjectPath [0x770D7A6E+238]

**Comment by Bruuuuuuce** [comment]
很抱歉，截图功能无法进行维护，建议弃用选择微信通知方案
