### ISSUE TITLE
请问MacOS下如何取消定时运行呀？

### ISSUE THREAD

**Issue by James-Harden-13-R** [Bruuuuuuce/PKUAutoSubmit#34]
请问MacOS下如何取消定时运行呀？

文章说MacOS可以取消定时运行，不过没有说清楚如何取消？是要再运行一次 `./macAutoRun.sh` 命令吗，那要输入什么数字啊，感谢！

**Comment by Bruuuuuuce** [comment]
因为我没有mac系统的电脑，这个也不是我写的，所以看代码的话要简单点应该直接用命令"python3 cron.py -c"就好了吧？

**Comment by James-Harden-13-R** [comment]
> 因为我没有mac系统的电脑，这个也不是我写的，所以看代码的话要简单点应该直接用命令"python3 cron.py -c"就好了吧？

感谢！运行之后`python3 cron.py -c`显示：
“环境检查通过
成功清除4项定时任务~”

应该是搞定了！

**Comment by ErnestDong** [comment]
crontab -e

然后删除掉那一行就好了

**Comment by Bruuuuuuce** [comment]
> crontab -e
> 
> 然后删除掉那一行就好了（dd是删除，然后:wq 退出)

在macAutoRun.sh中已提供相应快捷方法
