### ISSUE TITLE
貌似北大网盘的版本还没有更新

### ISSUE THREAD

**Issue by HuangLianzhe** [Bruuuuuuce/PKUAutoSubmit#6]
rt

**Comment by Bruuuuuuce** [comment]
了解，更新到了2.0，现已更新

发件人: Huang Lianzhe
发送时间: 2020年10月11日 23:05
收件人: Bruuuuuuce/PKUAutoSubmit
抄送: Subscribed
主题: [Bruuuuuuce/PKUAutoSubmit] 貌似北大网盘的版本还没有更新 (#6)

rt

**Comment by HuangLianzhe** [comment]
ok, 辛苦啦

**Comment by Bruuuuuuce** [comment]
没事，毕竟这部分代码都是大佬您写的，话说树洞各种形式推广被删了n次就离谱TT

发件人: Huang Lianzhe
发送时间: 2020年10月12日 9:21
收件人: Bruuuuuuce/PKUAutoSubmit
抄送: Bruce Ding; Comment
主题: Re: [Bruuuuuuce/PKUAutoSubmit] 貌似北大网盘的版本还没有更新 (#6)

ok, 辛苦啦
