### ISSUE TITLE
ubuntu系统下的执行问题

### ISSUE THREAD

**Issue by mojave-pku** [Bruuuuuuce/PKUAutoSubmit#7]
PhantomJS的版本不对，报执行格式错误。包里带的PhantomJS应该是macOS版的。我到官网下了个Linux版本的就正常了。
或许可以把PhantomJS替换一下，单发个Linux版，毕竟挂阿里云腾讯云的学生机比挂自己电脑上稳定（

**Comment by Bruuuuuuce** [comment]
我之前忘了PhantomJS还有Linux版，确实可以如此操作，大佬可以加一个进去，我再release一个Linux版，不过稳定性现在应该已经不错了

发件人: Huang Lianzhe
发送时间: 2020年10月12日 9:25
收件人: Bruuuuuuce/PKUAutoSubmit
抄送: Subscribed
主题: [Bruuuuuuce/PKUAutoSubmit] ubuntu系统下的执行问题 (#7)

PhantomJS的版本不对，报执行格式错误。包里带的PhantomJS应该是macOS版的。我到官网下了个Linux版本的就正常了。
或许可以把PhantomJS替换一下，单发个Linux版，毕竟挂阿里云腾讯云的学生机比挂自己电脑上稳定（

**Comment by HuangLianzhe** [comment]
这个就交给你啦。
不过我其实建议把PhantomJS从git包里拿掉，在release里放就好了。然后运行前环境检查里加一下提示，可以在哪里下载。不然每次git clone都好慢。
如果你想拿掉的话可能还要看看怎么把这个文件从git的历史记录里拿掉（有点麻烦），不然没差（git保留所有编辑历史记录）。
保持现状也OK。

**Comment by Bruuuuuuce** [comment]
了解

发件人: Huang Lianzhe
发送时间: 2020年10月12日 9:36
收件人: Bruuuuuuce/PKUAutoSubmit
抄送: Bruce Ding; Comment
主题: Re: [Bruuuuuuce/PKUAutoSubmit] ubuntu系统下的执行问题 (#7)

这个就交给你啦。
不过我其实建议把PhantomJS从git包里拿掉，在release里放就好了。然后运行前环境检查里加一下提示，可以在哪里下载。不然每次git clone都好慢。
如果你想拿掉的话可能还要看看怎么把这个文件从git的历史记录里拿掉（有点麻烦），不然没差（git保留所有编辑历史记录）。
保持现状也OK。
