### ISSUE TITLE
关于README（不成熟的小提议）

### ISSUE THREAD

**Issue by burning846** [Bruuuuuuce/PKUAutoSubmit#8]
感觉README里写现在的feature就好了吧，剩下的都写在update log里，再加上log的日期，不然分不清哪些是现在的bug哪些是已修复哪些是feature，有点晕

**Comment by hayschan** [comment]
+1，建议删掉readme开头的那堆 update，加一个特性的部分。

**Comment by wr786** [comment]
+1，此外还可以多利用`release`功能，在`release`的相关描述中同时写上更新内容（也可以把鸣谢写到这里

**Comment by Bruuuuuuce** [comment]
了解，在一定时间之后改回常规版的project
