### ISSUE TITLE
厚颜无耻地求一发推广

### ISSUE THREAD

**Issue by YOUSIKI** [Bruuuuuuce/PKUAutoSubmit#9]
做了一点微小的改动，每天通过 Github Actions 自动执行，连电脑都不需要开了 🤪

https://github.com/YOUSIKI/PKUAutoSubmit

**Comment by hayschan** [comment]
还能这样，从来没用过Github Actions 🐂啊，我都是在VPS跑

**Comment by YOUSIKI** [comment]
VPS 要钱的啊，QwQ

**Comment by Bruuuuuuce** [comment]
大佬🐂🍺，太聚了

**Comment by Bruuuuuuce** [comment]
已加入README

发件人: YOUSIKI
发送时间: 2020年10月13日 11:38
收件人: Bruuuuuuce/PKUAutoSubmit
抄送: Subscribed
主题: [Bruuuuuuce/PKUAutoSubmit] 厚颜无耻地求一发推广 (#9)

做了一点微小的改动，每天通过 Github Actions 自动执行，连电脑都不需要开了 🤪
https://github.com/YOUSIKI/PKUAutoSubmit

**Comment by hayschan** [comment]
> VPS 要钱的啊，QwQ

GitHub actions 如何运行？我的好像没自动跑。
![image](https://user-images.githubusercontent.com/25737801/95945669-944f5680-0e1d-11eb-9126-5b65192e51cc.png)
不像你的：
![image](https://user-images.githubusercontent.com/25737801/95945706-a5986300-0e1d-11eb-8e82-40bbc05e934c.png)

**Comment by Bruuuuuuce** [comment]
> > VPS 要钱的啊，QwQ
> 
> GitHub actions 如何运行？我的好像没自动跑。
> ![image](https://user-images.githubusercontent.com/25737801/95945669-944f5680-0e1d-11eb-9126-5b65192e51cc.png)
> 不像你的：
> ![image](https://user-images.githubusercontent.com/25737801/95945706-a5986300-0e1d-11eb-8e82-40bbc05e934c.png)

我还没试，可以去作者那里report一下

**Comment by YOUSIKI** [comment]
> > > VPS 要钱的啊，QwQ
> > 
> > 
> > GitHub actions 如何运行？我的好像没自动跑。
> > ![image](https://user-images.githubusercontent.com/25737801/95945669-944f5680-0e1d-11eb-9126-5b65192e51cc.png)
> > 不像你的：
> > ![image](https://user-images.githubusercontent.com/25737801/95945706-a5986300-0e1d-11eb-8e82-40bbc05e934c.png)
> 
> 我还没试，可以去作者那里report一下

可能Fork之后需要先手动随便PUSH一次触发Actions，然后就自动执行了。我也不太确定Github Actions这个Cron机制……

**Comment by mojave-pku** [comment]
今天试用了一下，能用。这个太舒服啦。感谢大佬！
只是你那个Fork出去的库，4Star/15Fork，惨案啊hhhh

**Comment by Bruuuuuuce** [comment]
> 今天试用了一下，能用。这个太舒服啦。感谢大佬！
> 只是你那个Fork出去的库，4Star/15Fork，惨案啊hhhh

确实大佬，我已经在readme最上面安利了，不过Fork是原项目的Fork数，谁Fork去显示都一样的

**Comment by mojave-pku** [comment]
> > 今天试用了一下，能用。这个太舒服啦。感谢大佬！
> > 只是你那个Fork出去的库，4Star/15Fork，惨案啊hhhh
> 
> 确实大佬，我已经在readme最上面安利了，不过Fork是原项目的Fork数，谁Fork去显示都一样的

阿原来是这样！

**Comment by neko-kira** [comment]
请问一下，在触发action后会报错？这个是什么原因造成的呢？
![图片](https://user-images.githubusercontent.com/37890888/96282035-beb33680-100c-11eb-8fdc-5ce5fcc4d537.png)

**Comment by YOUSIKI** [comment]
> 请问一下，在触发action后会报错？这个是什么原因造成的呢？
> ![图片](https://user-images.githubusercontent.com/37890888/96282035-beb33680-100c-11eb-8fdc-5ce5fcc4d537.png)

貌似有的时候Actions服务器会抽风的样子，我也不清楚为什么，不过好在这种情况还比较少。而且运行失败会邮件通知，记得手动补一下就好。今天好像很多人的Actions都挂了。

**Comment by Bruuuuuuce** [comment]
> 请问一下，在触发action后会报错？这个是什么原因造成的呢？
> ![图片](https://user-images.githubusercontent.com/37890888/96282035-beb33680-100c-11eb-8fdc-5ce5fcc4d537.png)

感谢反馈，正在着手修复
